apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: init
spec:
  description: >-
    App Studio Initialize Pipeline Task, include flags for rebuild and auth.
  params:
    - name: image-url
      description: Image URL for testing
    - name: rebuild
      description: Rebuild the image if exists
      default: "false"
  results:
    - name: build
  steps:
    - name: appstudio-init
      image: registry.access.redhat.com/ubi8/skopeo@sha256:da250dddad75927f10e882125d8c6a10bad12c575374c8c6aae7eee77647b060
      script: |
        #!/bin/bash
        echo "App Studio Build Initialize: $(params.image-url)"
        echo
        echo "Determine if Image Already Exists"
        # Build the image when image does not exists or rebuild is set to true
        if ! skopeo inspect --no-tags docker://$(params.image-url) &>/dev/null || [ "$(params.rebuild)" == "true" ]; then
          echo -n "true" > $(results.build.path)
        else
          echo -n "false" > $(results.build.path)
        fi
